<html>
<head>
<title>TestNG:  Regression</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Regression</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>20/10/1</td>
</tr><tr>
<td>Started on:</td><td>Wed May 04 09:25:26 IST 2022</td>
</tr>
<tr><td>Total time:</td><td>17 seconds (17839 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='assertion.AssertionClass.A()'><b>A</b><br>Test class: assertion.AssertionClass</td>
<td><div><pre>java.lang.AssertionError: did not expect [450] but found [450]
	at assertion.AssertionClass.A(AssertionClass.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace173642112", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace173642112'><pre>java.lang.AssertionError: did not expect [450] but found [450]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failEquals(Assert.java:1041)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
	at org.testng.Assert.assertNotEquals(Assert.java:1531)
	at org.testng.Assert.assertNotEquals(Assert.java:1535)
	at assertion.AssertionClass.A(AssertionClass.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.AssertionClass@1f57539</td></tr>
<tr>
<td title='enable.EnabledInTestNG.A()'><b>A</b><br>Test class: enable.EnabledInTestNG</td>
<td><div><pre>java.lang.AssertionError: did not expect [450] but found [450]
	at enable.EnabledInTestNG.A(EnabledInTestNG.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace493862501", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace493862501'><pre>java.lang.AssertionError: did not expect [450] but found [450]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failEquals(Assert.java:1041)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
	at org.testng.Assert.assertNotEquals(Assert.java:1531)
	at org.testng.Assert.assertNotEquals(Assert.java:1535)
	at enable.EnabledInTestNG.A(EnabledInTestNG.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>enable.EnabledInTestNG@4493d195</td></tr>
<tr>
<td title='assertion.SoftAssertionClass.A()'><b>A</b><br>Test class: assertion.SoftAssertionClass</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	expected [4500] but found [450],
	did not expect [450] but found [450]
	at assertion.SoftAssertionClass.A(SoftAssertionClass.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1198385883", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1198385883'><pre>java.lang.AssertionError: The following asserts failed:
	expected [4500] but found [450],
	did not expect [450] but found [450]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at assertion.SoftAssertionClass.A(SoftAssertionClass.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.SoftAssertionClass@76f2b07d</td></tr>
<tr>
<td title='assertion.AssertionClass.B()'><b>B</b><br>Test class: assertion.AssertionClass</td>
<td><div><pre>java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
	at assertion.AssertionClass.B(AssertionClass.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1630051201", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1630051201'><pre>java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertFalse(Assert.java:67)
	at assertion.AssertionClass.B(AssertionClass.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.AssertionClass@1f57539</td></tr>
<tr>
<td title='enable.EnabledInTestNG.B()'><b>B</b><br>Test class: enable.EnabledInTestNG</td>
<td><div><pre>java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
	at enable.EnabledInTestNG.B(EnabledInTestNG.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1501012371", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1501012371'><pre>java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertFalse(Assert.java:67)
	at enable.EnabledInTestNG.B(EnabledInTestNG.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>enable.EnabledInTestNG@4493d195</td></tr>
<tr>
<td title='assertion.SoftAssertionClass.B()'><b>B</b><br>Test class: assertion.SoftAssertionClass</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	User is displayed after deletion expected [false] but found [true]
	at assertion.SoftAssertionClass.B(SoftAssertionClass.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace592006933", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace592006933'><pre>java.lang.AssertionError: The following asserts failed:
	User is displayed after deletion expected [false] but found [true]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at assertion.SoftAssertionClass.B(SoftAssertionClass.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.SoftAssertionClass@76f2b07d</td></tr>
<tr>
<td title='invocation.InvocationInTestNG.sampleTestCase()'><b>sampleTestCase</b><br>Test class: invocation.InvocationInTestNG</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at invocation.InvocationInTestNG.sampleTestCase(InvocationInTestNG.java:16)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1678787772", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1678787772'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at invocation.InvocationInTestNG.sampleTestCase(InvocationInTestNG.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>invocation.InvocationInTestNG@4232c52b</td></tr>
<tr>
<td title='dependent.DependentTestCasesInTestNG.verifyUserCanBeEdited()'><b>verifyUserCanBeEdited</b><br>Test class: dependent.DependentTestCasesInTestNG</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at dependent.DependentTestCasesInTestNG.verifyUserCanBeEdited(DependentTestCasesInTestNG.java:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace245712958", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace245712958'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at dependent.DependentTestCasesInTestNG.verifyUserCanBeEdited(DependentTestCasesInTestNG.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>dependent.DependentTestCasesInTestNG@2781e022</td></tr>
<tr>
<td title='assertion.AssertionClass.verifyUserCanUploadFile()'><b>verifyUserCanUploadFile</b><br>Test class: assertion.AssertionClass</td>
<td><div><pre>java.lang.AssertionError: Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@79360a39]
	at assertion.AssertionClass.verifyUserCanUploadFile(AssertionClass.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace146436473", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace146436473'><pre>java.lang.AssertionError: Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@79360a39]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotSame(Assert.java:1033)
	at org.testng.Assert.assertNull(Assert.java:965)
	at assertion.AssertionClass.verifyUserCanUploadFile(AssertionClass.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.AssertionClass@1f57539</td></tr>
<tr>
<td title='assertion.SoftAssertionClass.verifyUserCanUploadFile()'><b>verifyUserCanUploadFile</b><br>Test class: assertion.SoftAssertionClass</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@28467807]
	at assertion.SoftAssertionClass.verifyUserCanUploadFile(SoftAssertionClass.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1297248341", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1297248341'><pre>java.lang.AssertionError: The following asserts failed:
	Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@28467807]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at assertion.SoftAssertionClass.verifyUserCanUploadFile(SoftAssertionClass.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>assertion.SoftAssertionClass@76f2b07d</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='annotations.AnnotationsTestNG.A()'><b>A</b><br>Test class: annotations.AnnotationsTestNG</td>
<td></td>
<td>0</td>
<td>annotations.AnnotationsTestNG@536aaa8d</td></tr>
<tr>
<td title='priority.PriorityInTestNG.A()'><b>A</b><br>Test class: priority.PriorityInTestNG</td>
<td></td>
<td>0</td>
<td>priority.PriorityInTestNG@1877ab81</td></tr>
<tr>
<td title='annotations.AnnotationsTestNG.B()'><b>B</b><br>Test class: annotations.AnnotationsTestNG</td>
<td></td>
<td>0</td>
<td>annotations.AnnotationsTestNG@536aaa8d</td></tr>
<tr>
<td title='priority.PriorityInTestNG.B()'><b>B</b><br>Test class: priority.PriorityInTestNG</td>
<td></td>
<td>0</td>
<td>priority.PriorityInTestNG@1877ab81</td></tr>
<tr>
<td title='dataprovider.DataProviderInTestNG.addNewUserInSystem()'><b>addNewUserInSystem</b><br>Test class: dataprovider.DataProviderInTestNG<br>Parameters: Amit, patil, amit@patil.com, 23, 34567, IT</td>
<td></td>
<td>0</td>
<td>dataprovider.DataProviderInTestNG@704a52ec</td></tr>
<tr>
<td title='dataprovider.DataProviderInTestNG.addNewUserInSystem()'><b>addNewUserInSystem</b><br>Test class: dataprovider.DataProviderInTestNG<br>Parameters: Amol, Pawar, amol@pawar.com, 45, 44567, Software</td>
<td></td>
<td>0</td>
<td>dataprovider.DataProviderInTestNG@704a52ec</td></tr>
<tr>
<td title='dataprovider.DataProviderInTestNG2.addNewUserInSystem()'><b>addNewUserInSystem</b><br>Test class: dataprovider.DataProviderInTestNG2<br>Parameters: Amit, patil, amit@patil.com, 23, 34567, IT</td>
<td></td>
<td>2</td>
<td>dataprovider.DataProviderInTestNG2@6ee52dcd</td></tr>
<tr>
<td title='dataprovider.DataProviderInTestNG2.addNewUserInSystem()'><b>addNewUserInSystem</b><br>Test class: dataprovider.DataProviderInTestNG2<br>Parameters: Amol, Pawar, amol@pawar.com, 45, 44567, Software</td>
<td></td>
<td>3</td>
<td>dataprovider.DataProviderInTestNG2@6ee52dcd</td></tr>
<tr>
<td title='invocation.InvocationInTestNG.sampleTestCase()'><b>sampleTestCase</b><br>Test class: invocation.InvocationInTestNG</td>
<td></td>
<td>0</td>
<td>invocation.InvocationInTestNG@4232c52b</td></tr>
<tr>
<td title='invocation.InvocationInTestNG.sampleTestCase()'><b>sampleTestCase</b><br>Test class: invocation.InvocationInTestNG</td>
<td></td>
<td>0</td>
<td>invocation.InvocationInTestNG@4232c52b</td></tr>
<tr>
<td title='invocation.InvocationInTestNG.sampleTestCase()'><b>sampleTestCase</b><br>Test class: invocation.InvocationInTestNG</td>
<td></td>
<td>0</td>
<td>invocation.InvocationInTestNG@4232c52b</td></tr>
<tr>
<td title='invocation.InvocationInTestNG.sampleTestCase()'><b>sampleTestCase</b><br>Test class: invocation.InvocationInTestNG</td>
<td></td>
<td>0</td>
<td>invocation.InvocationInTestNG@4232c52b</td></tr>
<tr>
<td title='brockenlink.BrockenLinkClass.verifyURLIsBrockenOrNot()'><b>verifyURLIsBrockenOrNot</b><br>Test class: brockenlink.BrockenLinkClass</td>
<td></td>
<td>2</td>
<td>brockenlink.BrockenLinkClass@57e1b0c</td></tr>
<tr>
<td title='dependent.DependentTestCasesInTestNG.verifyUserCanBeAdded()'><b>verifyUserCanBeAdded</b><br>Test class: dependent.DependentTestCasesInTestNG</td>
<td></td>
<td>0</td>
<td>dependent.DependentTestCasesInTestNG@2781e022</td></tr>
<tr>
<td title='annotations.SampleAnnotationTestNG.verifyUserCanLoginWithValiedCredentials()'><b>verifyUserCanLoginWithValiedCredentials</b><br>Test class: annotations.SampleAnnotationTestNG</td>
<td></td>
<td>0</td>
<td>annotations.SampleAnnotationTestNG@e320068</td></tr>
<tr>
<td title='annotations.SampleAnnotationTestNG.verifyUserCanNotLoginWithInValiedCredentials()'><b>verifyUserCanNotLoginWithInValiedCredentials</b><br>Test class: annotations.SampleAnnotationTestNG</td>
<td></td>
<td>0</td>
<td>annotations.SampleAnnotationTestNG@e320068</td></tr>
<tr>
<td title='annotations.AnnotationsTestNG.verifyUserCanUploadFile()'><b>verifyUserCanUploadFile</b><br>Test class: annotations.AnnotationsTestNG</td>
<td></td>
<td>0</td>
<td>annotations.AnnotationsTestNG@536aaa8d</td></tr>
<tr>
<td title='priority.PriorityInTestNG.verifyUserCanUploadFile()'><b>verifyUserCanUploadFile</b><br>Test class: priority.PriorityInTestNG</td>
<td></td>
<td>0</td>
<td>priority.PriorityInTestNG@1877ab81</td></tr>
<tr>
<td title='assertion.AssertionClass.zTestCase()'><b>zTestCase</b><br>Test class: assertion.AssertionClass</td>
<td></td>
<td>0</td>
<td>assertion.AssertionClass@1f57539</td></tr>
<tr>
<td title='assertion.SoftAssertionClass.zTestCase()'><b>zTestCase</b><br>Test class: assertion.SoftAssertionClass</td>
<td></td>
<td>0</td>
<td>assertion.SoftAssertionClass@76f2b07d</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='dependent.DependentTestCasesInTestNG.verifyUserCanBeDeleted()'><b>verifyUserCanBeDeleted</b><br>Test class: dependent.DependentTestCasesInTestNG</td>
<td><div><pre>java.lang.Throwable: Method DependentTestCasesInTestNG.verifyUserCanBeDeleted()[pri:0, instance:dependent.DependentTestCasesInTestNG@2781e022] depends on not successfully finished methods
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 3 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace918962845", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace918962845'><pre>java.lang.Throwable: Method DependentTestCasesInTestNG.verifyUserCanBeDeleted()[pri:0, instance:dependent.DependentTestCasesInTestNG@2781e022] depends on not successfully finished methods
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
</pre></div></td>
<td>0</td>
<td>dependent.DependentTestCasesInTestNG@2781e022</td></tr>
</table><p>
</body>
</html>