<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="3" name="Regression(failed)" tests="16" failures="10" timestamp="2022-05-04T09:19:41 IST" time="0.349" errors="0">
  <testcase name="B" time="0.017" classname="enable.EnabledInTestNG">
    <failure type="java.lang.AssertionError" message="User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
at enable.EnabledInTestNG.B(EnabledInTestNG.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="A" time="0.013" classname="enable.EnabledInTestNG">
    <failure type="java.lang.AssertionError" message="did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: did not expect [450] but found [450]
at enable.EnabledInTestNG.A(EnabledInTestNG.java:31)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="B" time="0.019" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User is displayed after deletion expected [false] but found [true]
at assertion.SoftAssertionClass.B(SoftAssertionClass.java:24)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="A" time="0.007" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [4500] but found [450],
	did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [4500] but found [450],
did not expect [450] but found [450]
at assertion.SoftAssertionClass.A(SoftAssertionClass.java:42)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="verifyUserCanUploadFile" time="0.01" classname="assertion.SoftAssertionClass">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@80169cf]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@80169cf]
at assertion.SoftAssertionClass.verifyUserCanUploadFile(SoftAssertionClass.java:53)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanUploadFile -->
  <testcase name="sampleTestCase" time="0.002" classname="invocation.InvocationInTestNG"/>
  <testcase name="sampleTestCase" time="0.012" classname="invocation.InvocationInTestNG"/>
  <testcase name="sampleTestCase" time="0.001" classname="invocation.InvocationInTestNG">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at invocation.InvocationInTestNG.sampleTestCase(InvocationInTestNG.java:16)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sampleTestCase -->
  <testcase name="sampleTestCase" time="0.006" classname="invocation.InvocationInTestNG"/>
  <testcase name="sampleTestCase" time="0.001" classname="invocation.InvocationInTestNG"/>
  <testcase name="verifyUserCanBeAdded" time="0.003" classname="dependent.DependentTestCasesInTestNG"/>
  <testcase name="verifyUserCanBeEdited" time="0.002" classname="dependent.DependentTestCasesInTestNG">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at dependent.DependentTestCasesInTestNG.verifyUserCanBeEdited(DependentTestCasesInTestNG.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanBeEdited -->
  <testcase name="verifyUserCanBeDeleted" time="0.0" classname="dependent.DependentTestCasesInTestNG">
    <skipped/>
  </testcase> <!-- verifyUserCanBeDeleted -->
  <testcase name="verifyUserCanUploadFile" time="0.009" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@4b9e255]">
      <![CDATA[java.lang.AssertionError: Object got initialized falsly expected [null] but found [ktctc.DM21MavenProject.FileUploadClass@4b9e255]
at assertion.AssertionClass.verifyUserCanUploadFile(AssertionClass.java:43)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanUploadFile -->
  <testcase name="B" time="0.005" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="User is displayed after deletion expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: User is displayed after deletion expected [false] but found [true]
at assertion.AssertionClass.B(AssertionClass.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- B -->
  <testcase name="A" time="0.004" classname="assertion.AssertionClass">
    <failure type="java.lang.AssertionError" message="did not expect [450] but found [450]">
      <![CDATA[java.lang.AssertionError: did not expect [450] but found [450]
at assertion.AssertionClass.A(AssertionClass.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="zTestCase" time="0.0" classname="assertion.AssertionClass">
    <ignored/>
  </testcase> <!-- zTestCase -->
  <testcase name="zTestCase" time="0.0" classname="enable.EnabledInTestNG">
    <ignored/>
  </testcase> <!-- zTestCase -->
  <testcase name="zTestCase" time="0.0" classname="assertion.SoftAssertionClass">
    <ignored/>
  </testcase> <!-- zTestCase -->
</testsuite> <!-- Regression(failed) -->
